# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Cheng-An Yang
tagline:             'Passionate about Science and Technology'
description:         'I am Cheng-An, an Engineer who''s passionate about science and technology.'
url:                 http://rhymer.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Cheng-An Yang'
  url:               http://rhymer.github.io
  email:             rhymer123@gmail.com

# Custom vars
version:             0.0.1

github:
  repo:           https://github.com/rhymer
